### ISSUE TITLE
STD r1 needs to be made.

### ISSUE THREAD

**Issue by Jellyfish-Red** [plasmavisgroup/PlasmaGraph#11]
The STD is the last document that we need to work on before this Senior Project can be considered finished. Details on its structure are in the "specs" sub-folder.

**Comment by Jellyfish-Red** [comment]
STD is being finished. ETA is Monday or Tuesday.

**Comment by danielquintini** [comment]
Finished PDF version of STD-3-2014-05-15 and Attachments.
